### ISSUE TITLE
Not detecting input on Mac OSX 10.10.5

### ISSUE THREAD

**Issue by GeekGuy96** [jkuhlmann/gainput#10]
Title pretty much says it all. Everything builds just find, I can setup an input manager and map inputs, but when I check for input, nothing happens.

**Comment by jkuhlmann** [comment]
Could you elaborate on which input devices you use? Mouse? Keyboard? Gamepad? 

Also, it sounds like it might work for you on other versions of OS X. Does it?

**Comment by GeekGuy96** [comment]
I've tried detecting keyboard and mouse input. And I have not tried it on any other version of Mac OSX. I'm sorry if this is all quite vague, I just don't have much to supply in terms of information about what's going on.

**Comment by jkuhlmann** [comment]
Sorry, I can only poke around as I don't have a Mac here right now to test. Do you have a window? The window has to be active ("key" in the OS X terms) in order to receive input events.

You could also try placing some breakpoints to see where it goes wrong. For keyboard inputs, the function OnDeviceInput() in lib/source/gainput/keyboard/GainputInputDeviceKeyboardMac.cpp should be called. For mouse inputs, MouseTap() in lib/source/gainput/mouse/GainputInputDeviceMouseMac.mm should be called.

**Comment by GeekGuy96** [comment]
I just finished trying to detect input in a Cocoa application written in Objective C++, just incase the window OpenGL / GLUT has created was some how causing a problem and I have the same issue, everything builds fine, but no input detection. I haven't messed around with the breakpoints much, but I'll give them a try in the morning.

**Comment by jkuhlmann** [comment]
Any news on this issue?

If you could send me (gainput@johanneskuhlmann.de) a minimal project that exhibits the problem, I could try reproducing it here.

**Comment by jkuhlmann** [comment]
I've just tested on 10.10.5 again and it works for me. Is anyone still having problems?
