### ISSUE TITLE
Programmatically trigger input events?

### ISSUE THREAD

**Issue by fohara** [jkuhlmann/gainput#11]
Cool project! Is it possible to programmatically trigger input events, such as a mouse click or key press? My use case is to listen for user input events, and then be able to replay those same input events programmatically. Also, is it possible to trigger input events directly (from a mouse, keyboard or gamepad) without the first step of listening for them?

Per the docs, I noticed one of the features is "Supports recording and playback of input sequences", and I wanted to make sure I was understanding that correctly. Thanks!

**Comment by jkuhlmann** [comment]
You probably want to use Gainput's recording and playback feature. You'll need a gainput::InputRecorder for hat (http://gainput.johanneskuhlmann.de/api/classgainput_1_1InputRecorder.html) and then a gainput::InputPlayer (http://gainput.johanneskuhlmann.de/api/classgainput_1_1InputPlayer.html) to play the recorded inputs. There is an example in the samples/recording/ folder (https://github.com/jkuhlmann/gainput/tree/master/samples/recording).

You have to create the devices with your InputManager both in order to record inputs as well as to play them back. The physical devices don't have to be present though for the playback as the recorded data will overwrite their state anyway.

Hope that helps!

**Comment by jkuhlmann** [comment]
How is it going?
